### PR TITLE
Fixed conflict with Python 3 http module

### PR DESCRIPTION
**Pull request by nm17**

### CODE REVIEW

**Comment by starek4** [comment]
I spend ~30min before I realize this namespace error. Please, merge this... 😄

**Comment by nm17** [comment]
Same happend to me :smile: 
I guess @jtpereyda forgot about this repo. I can fork this and merge this PR.

**Comment by starek4** [comment]
I will also add this example into Boofuzz examples folder 👍

**Review by starek4 — APPROVED** [review]

**Comment by jtpereyda** [comment]
@nm17 Thank you so much and sorry for the delay. I must have missed this notification way back. x_x Thanks @starek4 for the bump.

**Pull request merged**
